---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |>
  mutate(rating = review_scores_location / 2) |>
  select(
    rating, neighbourhood_group, neighbourhood,
    room_type, lat, long, price) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
  )
```

Use plotly to make some quick plots

```{r}
nyc_airbnb |> 
  mutate(text_label = 
           str_c("Price: ", price, 
                 "\nNeighborhood: ", neighbourhood)) |>
  plot_ly(
    x = ~lat, y=~long, color=~price, text = ~text_label,
    type = "scatter", mode = "markers", 
    alpha = 0.5
  )
```

with the text label, you can get extra info when hovering.

\n with the neighborhood is saying to make a new line.

```{r}
nyc_airbnb |>
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |>
  plot_ly(
    x = ~neighbourhood, y = ~price, color= ~neighbourhood,
    type = "box", colors = "viridis")
```

Lets do a bar chart with numbers of rentals

```{r}
nyc_airbnb |>
  count(neighbourhood) |>
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |>
  plot_ly(x = ~neighbourhood, y = ~n,
          type = "bar")
```

When you make your dashboard, you have to run this in the console: 

rmarkdown::render("dashboard.rmd", output_format = "flexdashboard::flex_dashboard")
